# Generated by Django 4.0.3 on 2022-04-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('address', models.TextField(max_length=250)),
                ('eventdescription', models.TextField(max_length=500)),
                ('eventlink', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.city')),
            ],
        ),
    ]
