# Generated by Django 4.0.3 on 2022-04-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_experiences_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='imagelink',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
